server:
  port: 8801 # & 8802 透过运行参数 --server.port 指定端口

eureka:
  instance:
    appname: feign-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8800/eureka/

spring:
  application:
    name: feign-service
