#!/bin/bash

history

# -l 参数，显示所有可选路径
showPaths(){
	echo -e "id\tpath"
	echo ${my_paths[@]}
	for i in $(seq 1 ${#my_paths[@]})
	do
		echo -e "$i\t${my_paths[$i]}"
	done
}

if [[ $1x = x ]]
then
	showPaths
else
	pwd
	echo ${my_paths[$1]}
	# cd ${my_paths[$1]}
	# cd . .
fi
