const ast = {
  type: 'File',
  start: 0,
  end: 168,
  loc: {
    start: { line: 1, column: 0 },
    end: { line: 16, column: 0 },
    filename: undefined,
    identifierName: undefined,
  },
  range: undefined,
  leadingComments: undefined,
  trailingComments: undefined,
  innerComments: undefined,
  extra: undefined,
  errors: [],
  program: {
    type: 'Program',
    start: 0,
    end: 168,
    loc: {
      start: [Position],
      end: [Position],
      filename: undefined,
      identifierName: undefined,
    },
    range: undefined,
    leadingComments: undefined,
    trailingComments: undefined,
    innerComments: undefined,
    extra: undefined,
    sourceType: 'module',
    interpreter: null,
    body: [
      {
        type: 'ExportDefaultDeclaration',
        start: 0,
        end: 167,
        loc: {
          start: [Position],
          end: [Position],
          filename: undefined,
          identifierName: undefined,
        },
        range: undefined,
        leadingComments: undefined,
        trailingComments: undefined,
        innerComments: undefined,
        extra: undefined,
        declaration: {
          type: 'ObjectExpression',
          start: 15,
          end: 167,
          loc: [SourceLocation],
          range: undefined,
          leadingComments: undefined,
          trailingComments: undefined,
          innerComments: undefined,
          extra: [Object],
          properties: [
            {
              type: 'ObjectMethod',
              start: 19,
              end: 66,
              loc: {
                start: [Position],
                end: [Position],
                filename: undefined,
                identifierName: undefined,
              },
              range: undefined,
              leadingComments: undefined,
              trailingComments: undefined,
              innerComments: undefined,
              extra: undefined,
              method: true,
              key: {
                type: 'Identifier',
                start: 19,
                end: 23,
                loc: [SourceLocation],
                range: undefined,
                leadingComments: undefined,
                trailingComments: undefined,
                innerComments: undefined,
                extra: undefined,
                name: 'data',
              },
              computed: false,
              kind: 'method',
              id: null,
              generator: false,
              async: false,
              params: [],
              body: {
                type: 'BlockStatement',
                start: 26,
                end: 66,
                loc: [SourceLocation],
                range: undefined,
                leadingComments: undefined,
                trailingComments: undefined,
                innerComments: undefined,
                extra: undefined,
                body: [Array],
                directives: [],
              },
            },
            {
              type: 'ObjectProperty',
              start: 70,
              end: 164,
              loc: {
                start: [Position],
                end: [Position],
                filename: undefined,
                identifierName: undefined,
              },
              range: undefined,
              leadingComments: undefined,
              trailingComments: undefined,
              innerComments: undefined,
              extra: undefined,
              method: false,
              key: {
                type: 'Identifier',
                start: 70,
                end: 77,
                loc: [SourceLocation],
                range: undefined,
                leadingComments: undefined,
                trailingComments: undefined,
                innerComments: undefined,
                extra: undefined,
                name: 'methods',
              },
              computed: false,
              shorthand: false,
              value: {
                type: 'ObjectExpression',
                start: 79,
                end: 164,
                loc: [SourceLocation],
                range: undefined,
                leadingComments: undefined,
                trailingComments: undefined,
                innerComments: undefined,
                extra: [Object],
                properties: [Array],
              },
            },
          ],
        },
      },
    ],
    directives: [],
  },
  comments: [],
}
