console.log('----- literal value -----')
console.log(`typeof 1: ${typeof 1}`)
console.log(`typeof '1': ${typeof '1'}`)
console.log(`typeof true: ${typeof true}`)
console.log(`typeof []: ${typeof []}`)
console.log(`typeof {}: ${typeof {}}`)
console.log(`typeof function () {}: ${typeof function () {}}`)
console.log(`typeof () => {}: ${typeof (() => {})}`)
console.log(`typeof null: ${typeof null}`)
console.log(`typeof undefined: ${typeof undefined}`)

console.log()
console.log('----- use constructor -----')
console.log(`typeof Number(1): ${typeof Number(1)}`)
console.log(`typeof new Number(1): ${typeof new Number(1)}`)
console.log(`typeof String('1'): ${typeof String('1')}`)
console.log(`typeof new String('1'): ${typeof new String('1')}`)
console.log(`typeof Boolean(true): ${typeof Boolean(true)}`)
console.log(`typeof new Boolean(true): ${typeof new Boolean(true)}`)
console.log(`typeof Array(10): ${typeof Array(10)}`)
console.log(`typeof new Array(10): ${typeof new Array(10)}`)
console.log(`typeof Object({}): ${typeof Object({})}`)
console.log(`typeof new Object({}): ${typeof new Object({})}`)

// console.log(`typeof function () {}: ${typeof function () {}}`)
// console.log(`typeof () => {}: ${typeof (() => {})}`)
// console.log(`typeof null: ${typeof null}`)
// console.log(`typeof undefined: ${typeof undefined}`)