server:
  port: 8803

eureka:
  instance:
    appname: feign-client
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8800/eureka/

spring:
  application:
    name: feign-client

# feign 配置
feign:
  client:
    config:
      default:
        # 超时设置
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic