import numpy as np

#array = np.array([[1,2,3],[4,5,6],[7,8,9]])
#print(array)

#print(array.flags)
#print(array.shape)
#print(array.strides)
#print(array.ndim)
#print(array.data)
#print(array.size)
#print(array.itemsize)
#print(array.nbytes)
#print(array.base)

#a = np.empty((2,4))
#print(a)
#a = np.zeros((3,2), dtype=np.int8)
#print(a)
#a = np.ones((3,3), dtype=np.complex)
#print(a)

#a = np.array([(1,2),(3,4),(5,6)], subok=False)
#print(a)
#print(a.base)

#array = np.array([1,2,3,4,5], dtype = np.complex)
#print(array)
#array = np.array([1,2,3], ndmin = 2)
#print(array)
#array = np.asarray([(1,2),(3,4, 5)])
#print(array)
#array = np.frombuffer(b'Hello World', dtype='S1', count=5)
#print(array)
#array = np.fromiter(iter(range(5)), dtype=float)
#print(array)

a = np.arange(1, 10)
print(a)
a = np.linspace(0, 10, endpoint=False, retstep = True)
print(a)
a = np.logspace(0, 10, num=11, base=2, dtype=np.int32)
print(a)