server:
  port: 8801 # 启动端口

eureka:
  instance:
    appname: service-provider # 实例名称
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/ # 注册中心

spring:
  application:
    name: service-provider # 服务名称